spring:
  application:
    name: user_service
  data:
    mongodb:
      uri: mongodb+srv://haoxugt_db_user:uon86ICxxfdwE8z7@user-data.k34ccrb.mongodb.net/?appName=user-data
      database: userdb


## postgresql configuration
#  datasource:
#    url: jdbc:postgresql://localhost:5432/ecom-user-db
#    username: haoxugt
#    password: password
#  jpa:
#    database: POSTGRESQL
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    show-sql: true
#    hibernate:
#      ddl-auto: update

## h2 database configuration
#  datasource:
#    url: jdbc:h2:mem:test
#  h2:
#    console:
#      enabled: true
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: create

server:
  port: 8082
